### ISSUE TITLE
openfl-gpg issue on lime > 2.5.2 and openfl > 3.2.2

### ISSUE THREAD

**Issue by xmorpher** [SempaiGames/extension-googleplaygames#11]
Hi, 
There's an issue with openfl-gpg 1.3.0 
in any lime > 2.5.2 and openfl > 3.2.2
for device Samsung S3 mini (android jelly bean, api 16) 
but it works on android 4.0 (android ice cream sandwich, api 14)...

An empty project with only the google play services init
crash the app in the api 16 device

It only crash in the haxelib versions:  lime > 2.5.2 and openfl > 3.2.2
 (without changing the code) it fails on
lime: 2.5.3, 2.6.0
openfl: 3.3.0, 3.3.1

[Maybe the lime was updated for the new android sdk
and is causing errors in newer api devices? ]

I only have 2 android devices to test: api 14, 16
(we have not tested on emulators)

in lime 2.5.2 and openfl 3.2.2 (and olders) the same project works on all mentioned devices

**Comment by fbricker** [comment]
Hi, are you using Lime next or Lime legacy?

**Comment by fbricker** [comment]
Hi, I'm closing the issue since we've released a new version of the library. If you're using openfl legacy and the issue persists after upgrading the extension, please let me know.
