### ISSUE TITLE
AppStateManager does not exist

### ISSUE THREAD

**Issue by rifai** [SempaiGames/extension-googleplaygames#14]
Hi, 
I tried to build simple android game using this extension. But I got this error 
    [javac] <my folder>\export\android\bin\deps\gpgex\src\com\gpgex\GooglePlayGames.java:18: package com.google.android.gms.appstate.AppStateManager does not exist

I already updated the latest Google Play Service library. I'm using version 1.3.1 from haxelib.

**Comment by fbricker** [comment]
Hi, I've fixed this last night. Please update the extension to version 1.3.2 to fix this (the issue was that google removed some APIs on the last version of google play services).

Thanks!
