### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by smks** [SempaiGames/extension-googleplaygames#15]
BUILD FAILED
C:\Development\Android SDK\tools\ant\build.xml:573: com.android.io.StreamException: java.io.FileNotFoundException: C:\Users\{ME}\Desktop\{PROJECT}\export\android\bin\deps\google-play-services_lib\AndroidManifest.xml (The system cannot find the file specified)
	at com.android.io.FileWrapper.getContents(FileWrapper.java:93)
	at com.android.xml.AndroidManifest.getStringValue(AndroidManifest.java:412)

**Comment by fbricker** [comment]
Hi, please provide details about your environment so we can try to help you.
Consider including:
1) haxe, nme and openfl version
2) if you're using openfl next or legacy
3) Do you have the last version of "google play services lib" installed from your android package manager?

Thanks

**Comment by smks** [comment]
My own error. Was pointing to a different Android SDK in my environment so wasn't including the library dependency. However I have found a bug relating to logging in, does crash my App. Will open a new issue tonight. Thanks!
