### ISSUE TITLE
 No resource found that matches the given name '@android:style/Theme.Material.Light.DialogWhenLarge.NoActionBar'.

### ISSUE THREAD

**Issue by smks** [SempaiGames/extension-googleplaygames#19]
[aapt] C:\Users\Shaun Stone\Desktop\RonnieRooster\compiled\android\bin\deps\google-play-services_lib\res\values-v21\appinvite_styles.xml:5: error
Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.Material.Light.DialogWhenLarge.NoActionBar'.
   [aapt]

**Comment by wikiti** [comment]
Same here. Tried to compile it with the `<android target-sdk-version="23"/>` in `application.xml`, and it seems to work.

Perhaps a versioning/deprecated error?

**Comment by smks** [comment]
Yeah it has something to do with using that. I have 23 working after grabbing the right SDK tools.

<android target-sdk-version="23"/>

**Comment by jhice** [comment]
I confirm it works starting from version 21 of the API, I use `<android target-sdk-version="21" />`

So it's more a SDK "issue" than an extension one. Perhaps we could change the theme in the manifest.xml (override it using this technique, bottom of the article : http://www.steverichey.com/dev/openfl-android-tips-and-tricks/) and changing the theme with something like : http://stackoverflow.com/questions/9767148/the-theme-in-manifest-xml ?

I dont know which theme would be compatible with the version 19 of the SDK and I did not try this.

**Comment by fbricker** [comment]
Hi, now this fix is documented.
I think google is pushing developers to use newer SDK by all means :/
