### ISSUE TITLE
Load resources from XML (Not required)

### ISSUE THREAD

**Issue by smks** [SempaiGames/extension-googleplaygames#22]
This seems like an unnecessary step for me. I have created a hash map that maps to the IDs of the achievements. This forces me to feed it XML instead of passing the ID directly.

var xmlText='......
                 <resources>
                <string name="complete stage 1">CgkI-7SKzbALA2IQAQ</string>
                <string name="kill 100 enemies">CgkI-7SKzbALA2IQBw</string>
                <string name="complete stage 2">CgkI-7SKzbALA2IQAg</string>
                 </resources>';

**Comment by fbricker** [comment]
Hi, load XML does exactly that (parses the XML into a hashmap). This is not mandatory, but we leave it there since looks useful (at lease it's useful for us)...
