### ISSUE TITLE
Android System Bar 

### ISSUE THREAD

**Issue by zoetbluez1** [SempaiGames/extension-googleplaygames#23]
Hi! Is there any way to make the system bar showing up when compiling with Android SDK 21 or higher! Thank you very much!

**Comment by fbricker** [comment]
Hi, I think you should address this question into openfl forums instead.
Have you tried setting fullscreen to false on your project.xml?

**Comment by zoetbluez1** [comment]
Hi, I still did not know this email, I'm not familiar to GitHub :). Thanks
for your reply and your awesome extensions. These help me to save many times

However it's not a big issues :) I will try to set fullscreen mode to false
in my project.xml.
Anyway, thank you very much!


2016-06-01 21:31 GMT+07:00 Federico Bricker <notifications@github.com>:
